package _2023_12_20.HW;

public enum NbaTeams {
    Atlanta_Hawks,
    Boston_Celtics,
    Brooklyn_Nets,
    Charlotte_Hornets,
    Chicago_Bulls,
    Cleveland_Cavaliers,
    Detroit_Pistons,
    Indiana_Pacers,
    Miami_Heat,
    Milwaukee_Bucks,
    NewYork_Knicks,
    Orlando_Magic,
    Philadelphia_76ers,
    Toronto_Raptors,
    Washington_Wizards,
    Dallas_Mavericks,
    Denver_Nuggets,
    GoldenState_Warriors,
    Houston_Rockets,
    LosAngeles_Clippers,
    LosAngeles_Lakers,
    Memphis_Grizzlies,
    Minnesota_Timberwolves,
    NewOrleans_Pelicans,
    OklahomaCity_Thunder,
    Phoenix_Suns,
    Portland_TrailBlazers,
    Sacramento_Kings,
    SanAntonio_Spurs,
    Utah_Jazz;
}
